#!/usr/bin/env python3
"""
Script to generate a nested Hiera-style inventory from a host list fetched via HTTP/HTTPS.
- Fetches hostnames from a specified URL (e.g., Management Host API).
- Parses hostnames to extract environment, group, and location information.
- Builds a nested dictionary structure suitable for Ansible inventory.
- Saves the final inventory to inventory/hosts.yml in YAML format.
2026-04-29 -- denis.walther@ionos.com
"""
import re
import sys
from pathlib import Path
import subprocess  # Used for curl calls, as requests will not work with PUKI
import yaml

# VARIABLES
MGMT_URL = "https://mgmt.example.com"
MGMT_URI = "/path/to/your/hostlist.txt"
OUTPUT_PATH = "inventory/00-autogenerated.yml"

class InventoryGenerator:
    """Generates a nested Hiera-style inventory from a host list fetched via HTTP/HTTPS."""
    def __init__(self, base_url, uri, output_path):
        self.source_url = f"{base_url.rstrip('/')}/{uri.lstrip('/')}"
        self.output_file = Path(output_path)
        # Level: Root and Environment (High-level)
        # This depends fully on your naming conventions, adjust as needed
        self.inventory = {
            'all': {
                'children': {
                    'qa': {'children': {}},
                    'pre': {'children': {}},
                    'live': {'children': {}},
                    'locations': {'children': {}}, 
                    'ungrouped': {'hosts': {}}
                }
            }
        }
        self.location_map = {
            # This depends fully on your naming conventions, adjust as needed
            'bap': 'bap_rhr_de',
            'bs': 'bs_kae_de',
        }

    def fetch_host_list(self):
        """Fetches the raw host list using the system's curl."""
        print(f"Fetching host list via curl from {self.source_url}...")
        try:
            result = subprocess.run(
                ["curl", "-sSL", self.source_url],
                capture_output=True,
                text=True,
                check=True,
                timeout=30
            )
            return result.stdout.splitlines()

        except subprocess.CalledProcessError as e:
            # specifically handle curl exit codes (e.g. 404, 500, SSL errors)
            print(f"ERROR: Curl failed (Exit {e.returncode}): {e.stderr}", file=sys.stderr)
            sys.exit(1)

        except (OSError, subprocess.SubprocessError) as e:
            # handle system-level issues (e.g. curl not installed, timeout)
            print(f"ERROR: System error during host fetch: {e}", file=sys.stderr)
            sys.exit(1)

    def parse_hostname(self, hostname: str) -> dict | None:
        """
        Final Surgical Parser:
        1. Hand-splits New format (hostqa001-bap-rhr-de)
        2. Regex for Old format (hostpre-bs01)
        3. Normalizes short codes (bap -> bap_rhr_de)
        """
        # Clean the hostname
        name = hostname.split('.')[0].lower()
        # Define Environment keywords (ordered by length to prevent 'pre' matching 'prelive')
        envs = ['prelive', 'pre', 'qa', 'live', 'prod', 'stg', 'test', 'dev']
        envs.sort(key=len, reverse=True)
        # This merges 'bap' hosts into the 'bap_rhr_de' group automatically
        # Only needed for the old naming convention, the new one does already have the full location in the name
        location_map = {
            # This depends fully on your naming conventions, adjust as needed
            'bap': 'bap_rhr_de',
            'bs': 'bs_kae_de'
            # Add more if needed
        }

        found_data = None

        # New Format (dash after digits)
        # Look for: group + env + digits + DASH + location
        # Example: hostqa001-bap-rhr-de
        new_match = re.search(r'([a-z0-9]+?)([a-z]+)\d+-(.+)', name)
        if new_match:
            env_candidate = new_match.group(2)
            if env_candidate in envs:
                found_data = {
                    'grp': new_match.group(1),
                    'env': env_candidate,
                    'loc': new_match.group(3).replace('-', '_')
                }

        # Old Format (digits at the very end)
        # Example: hostpre-bs01 or hostqa-bs01
        if not found_data:
            for env in envs:
                if env in name:
                    parts = name.split(env, 1)
                    grp = parts[0].rstrip('-')
                    # remainder is e.g., 'bs01' or '-bs01'
                    remainder = parts[1].lstrip('-')
                    # Remove digits at end: 'bs01' -> 'bs'
                    loc = re.sub(r'\d+$', '', remainder)

                    if loc:
                        found_data = {
                            'grp': grp or 'unknown',
                            'env': env,
                            'loc': loc.replace('-', '_')
                        }
                        break

        # Fallback (Just a dash, no env keyword)
        if not found_data and '-' in name:
            parts = name.split('-', 1)
            # Remove digits from the end of the location part
            loc = re.sub(r'\d+$', '', parts[1]).replace('-', '_')
            found_data = {
                'grp': parts[0],
                'env': 'live',
                'loc': loc
            }

        # FINAL NORMALIZATION
        if found_data:
            # Clean up the location string
            raw_loc = found_data['loc'].strip('_')
            # Example: If 'bap' is in our map, change it to 'bap_rhr_de'
            found_data['loc'] = location_map.get(raw_loc, raw_loc)
            return found_data

        return None

    def map_to_env_group(self, code):
        """Maps hostname codes (qa, pre, live) to inventory groups."""
        # This ensures 'live' stays 'live' and maps everything else correctly
        mapping = {
            'qa': 'qa', 
            'pre': 'pre', # prelive to pre
            'prelive': 'pre',# Normalizes both to pre
            'prod': 'live', 
            'live': 'live'
        }
        return mapping.get(code, code) # Return the code itself if not in mapping (handles 'live')

    def build_tree(self, hostnames: list[str]):
        """Builds trees with explicit type enforcement."""
        all_children = self.inventory['all']['children']

        for host in hostnames:
            host = host.strip()
            if not host or host.startswith('#'):
                continue

            data = self.parse_hostname(host)
            # This check is a 'Type Guard' for 'data'
            if data is None:
                all_children['ungrouped']['hosts'][host] = {}
                continue

            env_root: str = str(self.map_to_env_group(data.get('env', 'unknown')))
            grp_name: str = str(data.get('grp', 'unknown'))
            loc_name: str = str(data.get('loc', 'unknown'))

            # Ensure the Environment level exists
            env_level = all_children.setdefault(env_root, {'children': {}})
            # PRODUCT TREE
            cursor = env_level.setdefault('children', {})
            cursor = cursor.setdefault(grp_name, {'children': {}})['children']
            cursor = cursor.setdefault(f"{grp_name}_{env_root}", {'children': {}})['children']
            cursor.setdefault(f"{grp_name}_{env_root}_{loc_name}", {'hosts': {}})['hosts'][host] = {}

            # LOCATION TREE
            loc_root = all_children.setdefault('locations', {'children': {}})['children']
            loc_root.setdefault(loc_name, {'hosts': {}})['hosts'][host] = {}

    def save_to_disk(self):
        """Saves the final structure to inventory/auto_generated.yml."""
        self.output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self.output_file, 'w', encoding='utf-8') as f:
            yaml.dump(self.inventory, f, default_flow_style=False, sort_keys=False)
        print(f"Successfully saved nested inventory to: {self.output_file}")

    def print_summary(self):
        """Calculates and prints the total count of groups and hosts."""
        all_hosts = set()
        all_groups = set()
        # Define keywords to skip as a set for O(1) lookup speed
        excluded_keys = {"hosts", "children"}

        def walk(data, name):
            # Record the group name if it's not a structural keyword
            if name not in excluded_keys:
                all_groups.add(name)
            # If we find hosts, add them to our set
            if isinstance(data, dict):
                if "hosts" in data:
                    all_hosts.update(data["hosts"].keys())
                # Recurse into children
                if "children" in data:
                    for child_name, child_data in data["children"].items():
                        walk(child_data, child_name)

        # Start walking from the 'all' root
        walk(self.inventory["all"], "all")
        # Count ungrouped separately if they exist
        ungrouped_count = len(self.inventory["all"]["children"].get("ungrouped", {}).get("hosts", {}))

        print("\n" + "="*30)
        print("INVENTORY SUMMARY")
        print("="*30)
        print(f"Total Hosts:  {len(all_hosts)}")
        print(f"Total Groups: {len(all_groups)}")
        print(f"Ungrouped:    {ungrouped_count}")
        print("="*30 + "\n")

# Run the whole magic here!
if __name__ == "__main__":
    gen = InventoryGenerator(
        base_url=MGMT_URL,
        uri=MGMT_URI,
        output_path=OUTPUT_PATH
    )

    hosts = gen.fetch_host_list()
    # Uncomment if you think there are hosts missing
    # print(f"DEBUG: Fetched {len(hosts)} raw lines from URL")
    gen.build_tree(hosts)
    gen.save_to_disk()
    gen.print_summary()
